import Head from 'next/head'
import Navbar from './Navbar'

function PageLayout({ children }) {
    return (
        <div className="h-screen w-screen flex flex-col overflow-hidden">
            <Head>
                <title>CodeRecs</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Navbar />
            <div className="flex-1 p-5">{children}</div>
        </div>
    )
}

export default PageLayout
