import Head from 'next/head'

export default function Home() {
  return (
    <div className='grid place-items-center h-screen w-screen overflow-hidden'>
      <Head>
        <title>Coding Platform</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <p>Homepage</p>
      <p>Go to /editor/ide to see magic</p>
    </div>
  )
}
